### ISSUE TITLE
分析图表是怎么画的那么好的呢

### ISSUE THREAD

**Issue by whuhan2013** [airingursb/bilibili-user#1]
作者把数据存储在mysql中，怎么导出分析的

**Comment by airingursb** [comment]
@whuhan2013 分析图表可以使用Echarts画。
是的，用R语言导出分析，由于数据量太大，所以分两次导出，两次分析，最后统计

**Comment by whuhan2013** [comment]
'http://space.bilibili.com/ajax/member/GetInfo?mid=' + str(i)
这个URL失效了吧，
![Uploading p17.png…]()

**Comment by whuhan2013** [comment]
http://space.bilibili.com/ajax/member/MyInfo这个URL可以得到JSON数据
但是代码里的http://space.bilibili.com/ajax/member/GetInfo?mid=7243680却得到一个错误页面，而不是json数据，请问是B站改了结构了吗，还是要登陆什么的

**Comment by whuhan2013** [comment]
![p17](https://cloud.githubusercontent.com/assets/13049692/18503433/8842e5bc-7a8f-11e6-951e-8ecb6fe39fbe.png)

**Comment by airingursb** [comment]
@whuhan2013 我看了一下，它现在做了一些反爬虫的处理。
1. 这个 url 只能 post
2. 除了`mid`还接受了一个随机数参数`_`，测试之后发现每次请求这个参数的值都不一样。找了20分钟都没有找到这个参数在哪里出现，然后突然发现了，它是当前的时间戳。如`1473846755045`，它就是你发起请求的那一刻的时间戳（精确到毫秒），所以你只要请求的时候，程序生成个时间戳然后封装到post里就可以了。
3. 测试了一下，没有登录的 cookie 验证。
4. Header 要模拟一下，如图
![image](https://cloud.githubusercontent.com/assets/10513408/18508706/d3a2cfaa-7aa7-11e6-82b3-5e65a9c2365e.png)
。

**Comment by airingursb** [comment]
![](http://airing.ursb.me/image/2016091401.png)

**Comment by whuhan2013** [comment]
不好意思，我试了一下，还是不能成功，可能有些地方没考虑到，有时间的话可以更新一下源代码吗

**Comment by airingursb** [comment]
@whuhan2013 行，这周我找个空闲时间更新代码，更新好了通知你

**Comment by airingursb** [comment]
@whuhan2013 代码已更新。
