### ISSUE TITLE
请问为什么年龄抓到的没有年份呢只有日月呢？求解，谢谢谢谢谢

### ISSUE THREAD

**Issue by LaurenLuo** [airingursb/bilibili-user#10]
看到用户报告里面有年龄分析，但是抓到的birthday字段只有月份和日期，没有办法分析年龄呀，求教怎么获取年龄，非常感谢

**Comment by airingursb** [comment]
@LaurenLuo api改版了，现在是没有年份的了…

**Comment by airingursb** [comment]
@LaurenLuo 

有漏网之鱼，这个api还是可以看到生日的：http://interface.bilibili.com/card/%E6%80%95%E4%B8%8A%E7%81%AB%E6%9A%B4%E7%8E%8B%E8%80%81%E8%8F%8A.js?_=1490267774385

**Comment by xxw18217706879** [comment]
能私信么，我想了解你是怎么找到这个接口的。๛ก(ｰ̀ωｰ́ก)

**Comment by airingursb** [comment]
@xxw18217706879 … 浏览器  在b站的用户界面，按F12，打开控制台，然后选择Network模块，慢慢找就行了……
