### ISSUE TITLE
error: ConnectionError

### ISSUE THREAD

**Issue by buzai** [airingursb/bilibili-user#13]
python3 
mysql
ubuntu16

how can i fix this error

**Comment by buzai** [comment]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='123.57.184.70', port=8081): Max retries exceeded with url: http://space.bilibili.com/ajax/member/GetInfo (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fad40bd7438>: Failed to establish a new connection: [Errno 111] Connection refused',)))

**Comment by buzai** [comment]
this is proxy error?

**Comment by airingursb** [comment]
@buzai Yes, you should stop using these proxy pool or replace an new proxy pool.

**Comment by buzai** [comment]
Thanks
