### ISSUE TITLE
Json解析失败

### ISSUE THREAD

**Issue by PopeJoey** [airingursb/bilibili-user#14]
b站可能已经更改了接口，求一份数据库的dump。

**Comment by BLMYX01** [comment]
这边也是遇到这个问题orz，能够爬取一段时间，过后就提示解码失败了

**Comment by PopeJoey** [comment]
(*╹▽╹*)楼主大大打算继续维护么

**Comment by airingursb** [comment]
@PopeJoey P 我刚看了一下，接口没有变化啊。。

![image](https://user-images.githubusercontent.com/10513408/30866595-53abe3e2-a29f-11e7-96f7-90043d7933b2.png)

**Comment by airingursb** [comment]
@BLMYX01 控制一下抓取的速度，太快之后会被ban，导致返回的不是json，所以会显示解析失败。
如果有必要，可以贴出错误提示和相关代码，好方便我去复现

**Comment by PopeJoey** [comment]
我这边从一开始第一个JSON就失败了ORZ
![1506496189](https://user-images.githubusercontent.com/19484363/30900311-2749fbe8-a396-11e7-9451-3a96f594813a.png)
我设置了断点进去追踪了一下，发现第一个Json.load哪里就直接报异常了，此时jscontent内容如下
![1506496152](https://user-images.githubusercontent.com/19484363/30900365-58555d54-a396-11e7-92cd-9c32aa424a85.png)

**Comment by airingursb** [comment]
@PopeJoey 我刚pull了一下 然后运行了一下没有任何问题啊- -
看你这个jscontent的内容，应该是被ban了之后显示的500界面吧？你可以换一个网络再试试

**Comment by BLMYX01** [comment]
@airingursb 非常感谢！确实是楼主大大你说的问题！这边爬虫新手而已不好意思感觉问了挺低级的问题orz

**Comment by BLMYX01** [comment]
@PopeJoey 需要先把proxies给换一下，有试着换过嘛？

**Comment by PopeJoey** [comment]
@BLMYX01 换了代理后，终于能够爬取一些内容了。另外一个问题，每个代理获取一些json后，就会被B站ban。

**Comment by airingursb** [comment]
@PopeJoey 这样就需要使用代理池了

close #14

**Comment by qqtanwei** [comment]
http://space.bilibili.com/ajax/member/GetInfo 接口已经改了。访问不了了。

**Comment by airingursb** [comment]
@qqtanwei 完全没问题啊

![image](https://user-images.githubusercontent.com/10513408/31647674-2f02679c-b2cf-11e7-8930-127b4f10c84b.png)

![image](https://user-images.githubusercontent.com/10513408/31647689-40051238-b2cf-11e7-8816-5d1b6541759d.png)

**Comment by xiaoli-chen** [comment]
对的，出生年份被隐去了，只剩月份和日期了
