### ISSUE TITLE
你好，会员注册时间获取有些问题。

### ISSUE THREAD

**Issue by SchwarzeKatze** [airingursb/bilibili-user#16]
我用fiddler获取json之后，请问注册时间是regtime=1406807890这个参数吗，后面的数字又是怎样转换成年月日的呢？希望可以解答一下我的疑惑，谢谢。

**Comment by airingursb** [comment]
@SchwarzeKatze 时间戳

**Comment by xiaoli-chen** [comment]
这是从1970年算起，到现在有多少秒。约定俗成的，虽然不是那么intuitive。
