### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by meikoul** [airingursb/bilibili-user#20]
![image](https://user-images.githubusercontent.com/21165904/34359308-d9fc0744-ea91-11e7-95f9-5d2f28e6b6bd.png)
为什么到这里就直接走错误处理了呢  报No JSON object could be decoded

**Comment by airingursb** [comment]
@meikoul 谢谢反馈，这个接口已经被关闭了，貌似就是这两天的事情（前两天我看还好好的）。
现在暴露的接口只能爬取用户的id、name、vip等级、用户的关注数与粉丝数，以及用户的视频列表。
很遗憾，用户的基本信息已经拿不到了。（可以理解，毕竟暴露用户基本信息是不必要也是不安全的行为，b站已经修复了他）
届时，我会再修改代码重新爬取一些数据。虽然比原来的少了，但希望仍然有研究价值。

**Comment by ZheYuuu** [comment]
@airingursb 
following和follower的接口为
'https://api.bilibili.com/x/relation/stat?vmid=' + str(mid) + '&jsonp=jsonp').text

请问新的数据接口怎么找？

**Comment by airingursb** [comment]
@meikoul 把代理删掉就可以跑了。
@ZheYuuu 就是楼主贴图的那段代码涉及的接口。

**Comment by ZheYuuu** [comment]
不用代理直接跑不是一会就被封了？
加随机间隔？

**Comment by airingursb** [comment]
@ZheYuuu 间隔5秒爬取一次是比较安全的

**Comment by ruanjunpeng** [comment]
@airingursb 把代理删掉还是报No JSON Object could be decoded
![image](https://user-images.githubusercontent.com/19966112/40700837-df5fe85e-640d-11e8-945a-e73f372e719c.png)
![image](https://user-images.githubusercontent.com/19966112/40700870-ff57823e-640d-11e8-88fc-0f46fb5b924b.png)
