### ISSUE TITLE
小白提一个问题w

### ISSUE THREAD

**Issue by VergeDX** [airingursb/bilibili-user#21]
在用Windows 8.1运行脚本的时候，有MySQL Error的提示，请问该怎样解决呢？
PS：Python 3.6.4，已经执行过pip install requests和pip install pymysql
还有，请问您当时跑这个脚本花了多长时间呢？

**Comment by airingursb** [comment]
@VergeDX 需要安装MySQL数据，并运行一下项目中的 sql 文件建一下表。
不限速七天吧
