### ISSUE TITLE
16年时真的只有2千万用户？

### ISSUE THREAD

**Issue by zhang0peter** [airingursb/bilibili-user#24]
现在已经用3亿用户了

**Comment by zhang0peter** [comment]
https://space.bilibili.com/299999999/#/已经有了

**Comment by airingursb** [comment]
@zhang0peter 恩，2016年初的时候开放了注册，2016年1月2月注册的从名称上可以看出来是机器人（僵尸粉或者是为了b站游戏刷的号），不止2000万这么多。因此可以推断现在的3亿也具有很多水分。

**Comment by zhang0peter** [comment]
感觉现在爬取用户信息好困难，我一天只能爬3万条。

**Comment by airingursb** [comment]
分布式吧，或者用动态VPS爬取 @zhang0peter
