### ISSUE TITLE
代理问题

### ISSUE THREAD

**Issue by imshadowurlight** [airingursb/bilibili-user#31]
爬虫没有跑起来,一直报错链接失败;
置换代理
    'http': 'http://111.230.84.45:80',
    'http': 'http://111.230.84.59:80',
    'http': 'http://111.230.85.89:80',
后问题解决.
刚入门爬虫,感谢分享

**Comment by airingursb** [comment]
嗯。代理那里是要经常换的，所以运行程序的时候最好都替换成自己刚找的代理 @imshadowurlight
