### ISSUE TITLE
数据库各字段的含义及数据问题

### ISSUE THREAD

**Issue by ever-lasting** [airingursb/bilibili-user#33]
爬取了五千多条数据，除了id、姓名、性别、face、注册时间、生日、签名、level等字段不同外，其余都相同，甚至 粉丝、关注、文章等字段都为0！！！请问一下这是什么情况？！另外，麻烦解释一下字段的含义，非常感谢！

**Comment by airingursb** [comment]
attentions 是关注的播单的id
其他的你都说出来了。

现在一些为0的字段代表被屏蔽了，已经爬不到了…
