### ISSUE TITLE
这段代码解释下

### ISSUE THREAD

**Issue by kyriej** [airingursb/bilibili-user#34]
ua.strip()[1:-1 - 1]

**Comment by JIMhackKING** [comment]
ua.strip() 是用来去除字符串前后的空格或者制表符，就是空的地方就去除掉，只留下有字符的地方，[1:-1 - 1] ……这个就有点奇怪了，其实就是 [1:-2] ，这个是 Python 的切片，意思就是提取列表中 第2个数据（索引为1）到倒数第二个数据（不包括倒数第二个），之后返回一个新列表。
个人感觉，开发者的代码结构很混乱，而且没有注释，没有任何关于代码的解释

**Comment by airingursb** [comment]
确实是有问题的，此行代码的出处是由 @cloudsere 同学贡献的重构代码：https://github.com/airingursb/bilibili-user/commit/05e7ed851c471d880029ca8553648987c9808470

此处估计是她写错了，多了一个-1，后来被 @adlinx 发现了问题：https://github.com/airingursb/bilibili-user/commit/05e7ed851c471d880029ca8553648987c9808470，但是他修改的不对，虽然避免了之前多出一个-1的 bug，但是语义有问题。

感谢提出，已修复。
也感谢两位同学贡献的代码。

**Comment by airingursb** [comment]
#41
