### ISSUE TITLE
连接数据库出错

### ISSUE THREAD

**Issue by wujiiachen** [airingursb/bilibili-user#36]
1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank, face, regtime, spacesta,                                 birthday, sign, l' at line 1"

**Comment by yueshao6800** [comment]
一样的错误，也是说sql错了

**Comment by airingursb** [comment]
亲测无问题。

**Comment by wujiiachen** [comment]
老哥你的sql版本是什么，会不会是新版的问题

**Comment by airingursb** [comment]
@wujiiachen MySQL 8.0 无问题。当年开发的时候是 MySQL 5.x  也是没有问题的

**Comment by airingursb** [comment]
#37
