### ISSUE TITLE
粉丝数以及关注数和文章阅读数无法获得

### ISSUE THREAD

**Issue by wujiiachen** [airingursb/bilibili-user#38]
改完数据库数据之后爬取数据发现粉丝数和关注数和文章数等等都是0，用try语句的错误返回看了一下显示Expecting value: line 1 column 1 (char 0)
但是我在浏览器里面输入request网址是正常的json文件。不清楚什么情况
错误代码
Succeed get user info: 0	1.0389645099639893
Expecting value: line 1 column 1 (char 0)
Succeed get user info: 1	3.0973610877990723
Expecting value: line 1 column 1 (char 0)
Succeed get user info: 2	4.11681866645813
Expecting value: line 1 column 1 (char 0)
Succeed get user info: 3	5.138977527618408
Expecting value: line 1 column 1 (char 0)

加过错误显示的源代码

                   try:
                        res = requests.get(
                            'https://api.bilibili.com/x/relation/stat?vmid=' + str(mid) + '&jsonp=jsonp').text
                        viewinfo = requests.get(
                            'https://api.bilibili.com/x/space/upstat?mid=' + str(mid) + '&jsonp=jsonp').text
                        js_fans_data = json.loads(res)
                        js_viewdata = json.loads(viewinfo)
                        following = js_fans_data['data']['following']
                        fans = js_fans_data['data']['follower']
                        archiveview = js_viewdata['data']['archive']['view']
                        article = js_viewdata['data']['article']['view']
                    except Exception as e:
                        print(e)
                        following = 0
                        fans = 0
                        archiveview = 0
                        article = 0

**Comment by airingursb** [comment]
@wujiiachen 看看新的用户数据文件，可能 b 站又改了字段名或者删除了这个字段

**Comment by wujiiachen** [comment]
找出原因了，请求文章的阅读数和视频播放数的那个链接现在也要加一个header里面包含referer和useragent才能获得json，不然返回的是个404页面
