### ISSUE TITLE
望增加一个爬取前在数据库检查是否重复的功能

### ISSUE THREAD

**Issue by DDavid233** [airingursb/bilibili-user#4]
在爬取之前查询数据库中是否存在此id，如果是则跳过爬取操作，如果否则继续爬取。

**Comment by Kmogrr** [comment]
try:
                    # 执行SQL语句
                    sql = "SELECT * FROM bilibili_user_info where  mid = " + str(mid)
                    cur.execute(sql)
                    # 获取所有记录列表
                    results = cur.fetchall()
                    if len(results) != 0:
                        pass

                except:
                    print("select error")
                    pass

**Comment by TSStudio** [comment]
设置mid为主键 这样一旦重复直接报错

**Comment by 0xAphrodite** [comment]
> 设置mid为主键 这样一旦重复直接报错

请问你还有爬取的数据吗

**Comment by 0xAphrodite** [comment]
>   try:
>                     # 执行SQL语句
>                     sql = "SELECT * FROM bilibili_user_info where  mid = " + str(mid)
>                     cur.execute(sql)
>                     # 获取所有记录列表
>                     results = cur.fetchall()
>                     if len(results) != 0:
>                         pass
> 
>                 except:
>                     print("select error")
>                     pass

请问你还有爬取的数据吗
