### ISSUE TITLE
请问连接失败什么问题

### ISSUE THREAD

**Issue by Joey-Hu** [airingursb/bilibili-user#44]
HTTPConnectionPool(host='218.85.133.62', port=80): Max retries exceeded with url: http://space.bilibili.com/ajax/member/GetInfo (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03939230>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接 尝试失败。',)))

**Comment by airingursb** [comment]
需要换一下代理池中的代理 或者直接不挂代理限速跑

**Comment by Joey-Hu** [comment]
我试一下，谢谢------------------ 原始邮件 ------------------
发件人: "Airing"<notifications@github.com>
发送时间: 2019年4月24日(星期三) 上午9:40
收件人: "airingursb/bilibili-user"<bilibili-user@noreply.github.com>;
抄送: "huhao"<1925595006@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [airingursb/bilibili-user] 请问连接失败什么问题 (#44)



需要换一下代理池中的代理 或者直接不挂代理限速跑
 
&mdash;
