### ISSUE TITLE
请问怎样绕过B站的反爬虫？

### ISSUE THREAD

**Issue by maoqxxmm** [airingursb/bilibili-user#7]
发现每次爬200条以后就会被封IP，也不知道具体是封多久。

**Comment by Voluter** [comment]
设置代理池，每次用不同的ip访问B站，同时不要访问的过于频繁

**Comment by airingursb** [comment]
@maoqxxmm 买个动态vps，定时任务+拨号精灵，每爬一段时间自动重拨换ip

**Comment by gorillazhip** [comment]
@Voluter 我看@airingursb爬取的速度非常快啊，4天爬了2000多万，我这一台机器一天才能爬1w左右，急死了，想问问sleep多久比较合适啊···

**Comment by airingursb** [comment]
@gorillazhip 5s一次请求比较合适，具体可以自己测试调整。因为现在在了反爬，所以速度必然有所限制……
