### ISSUE TITLE
http 状态码：200 但是 status : false

### ISSUE THREAD

**Issue by HeartBeautifulSoup** [airingursb/bilibili-user#8]
爬虫初学者，copy您的代码做了个测试，但是一时还找不出错误在哪，求指点

输出结果：
"F:\Program Files\python\python.exe" "F:/Program Files/py3/text/bilibiliAPI_1.py"
b'{"status":false,"data":"\\u53c2\\u6570\\u9519\\u8bef"}'

Process finished with exit code 0

以下是源码：
`import requests
import time
import datetime

def datetime_to_timestamp_in_milliseconds(d):
    current_milli_time = lambda: int(round(time.time() * 1000))
    return current_milli_time()
url = 'http://space.bilibili.com/ajax/member/GetInfo?mid=5025594&_='+str(datetime_to_timestamp_in_milliseconds(datetime.datetime.now()))

head ={
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36',
    'X-Requested-With': 'XMLHttpRequest',
    'Referer': 'http://space.bilibili.com/5025594/',
    'Origin': 'http://space.bilibili.com',
    'Host': 'space.bilibili.com',
    'AlexaToolbar-ALX_NS_PH': 'AlexaToolbar/alx-4.0',
    'Accept-Language': 'zh-CN,zh;q=0.8,en;q=0.6,ja;q=0.4',
    'Accept': 'application/json, text/javascript, */*; q=0.01',
}
jscontent = requests.post(url, headers=head).content
print(jscontent)`

**Comment by airingursb** [comment]
`jscontent = requests.post(url, headers=head).content`

这行代码是对的，确实需要post，但是你post方法调用的不对，没有传data。
你在url里面拼接的参数并不是post的，而是get的，那些参数不能拼接。

@HeartBeautifulSoup

**Comment by HeartBeautifulSoup** [comment]
那请问 我获得的生日年份都是 0000 - xx -xx   这是为什么？
'birthday': '0000-01-01' @airingursb

**Comment by airingursb** [comment]
@HeartBeautifulSoup  所有的生日都是吗？？……那可能他们服务端改了代码，不呈现用户生日

**Comment by HeartBeautifulSoup** [comment]
这样的，万分感谢你的指点，受教了 @airingursb
