### ISSUE TITLE
采集的数据中粉丝数都为0，注册时间都为1970-01-01

### ISSUE THREAD

**Issue by KasakiMizore** [airingursb/bilibili-user#90]
![image](https://user-images.githubusercontent.com/56972514/88628903-3003dd00-d0e1-11ea-9fb4-f1ba4fbc1a1c.png)
![image](https://user-images.githubusercontent.com/56972514/88628942-36925480-d0e1-11ea-805a-0a1d4d975bb7.png)

**Comment by airingursb** [comment]
生日数据已经被 B 站隐藏掉了；粉丝和关注可以通过其他手段去抓
